name: pangeo
channels:
  - conda-forge
dependencies:
  - python=3.6
  - xarray
  - dask-kubernetes
  - gcsfs
  - intake::intake-xarray
  - zarr
  - matplotlib
  - numcodecs
  - python-blosc
  - lz4
  - nomkl
  - nbserverproxy
  - jupyter
  - jupyterlab=0.35
  - jupyterlab_launcher
  - jupyter_client
  - ipywidgets
  - graphviz
  - nodejs
  - bokeh >=0.13.0
  - cloudpickle >=0.2.1
  - cytoolz >=0.7.3
  - distributed >=1.28.0
  - numpy >=1.13.0
  - pandas >=0.21.0
  - partd >=0.3.10
  - toolz >=0.7.3
  - pip:
    - kubernetes
    - graphviz
    - git+https://github.com/dask/dask
    - git+https://github.com/TomAugspurger/distributed.git@2602-schedule

