name: pangeo
channels:
  - conda-forge
dependencies:
  - python=3.7
  - xarray
  - gcsfs
  - zarr
  - nomkl
  - nbserverproxy
  - jupyter
  - jupyter_client
  - jupyterlab
  - ipywidgets
  - graphviz
  - bokeh >=0.13.0
  - numpy >=1.13.0
  - pandas >=0.21.0
  - partd >=0.3.10
  - click >=6.6
  - cloudpickle >=0.2.2
  - cytoolz >=0.7.4
  - msgpack-python
  - psutil >=5.0
  - pyyaml
  - six
  - sortedcontainers !=2.0.0,!=2.0.1
  - tblib
  - toolz >=0.7.4
  - tornado==6.0.3
  - zict >=0.1.3
  - dask-kubernetes
  - xarray
  - zarr
  - pip:
    - kubernetes
    - graphviz
    - git+https://github.com/dask/dask
    - git+https://github.com/TomAugspurger/distributed.git@debug-comm-closed
