name: pangeo
channels:
  - conda-forge
dependencies:
  - python=3.7
  - nomkl
  - jupyter
  - jupyter_client
  - jupyterlab
  - ipywidgets
  - graphviz
  - bokeh >=0.13.0
  - numpy >=1.13.0
  - dask-ml
  - xgboost
  - scikit-learn
  - joblib
  - pip:
    - kubernetes
    - graphviz
    - git+https://github.com/dask/dask
    - git+https://github.com/dask/distributed
