#!/bin/bash
jupyter serverextension enable --py nbserverproxy --sys-prefix
jupyter labextension install @jupyter-widgets/jupyterlab-manager \
                             @jupyterlab/hub-extension@1.0.0-alpha.6 \
                             @pyviz/jupyterlab_pyviz \
                             jupyter-leaflet \
                             dask-labextension@1.0.0-rc.0

#EOF
